FROM almalinux 

#CMD ["ping", "-c5", "google.com"]

#ENTRYPOINT ["ping", "-c5", "google.com"]


#if you want to over-ride the entrypoint then pass the argument from cmd to entrypoint ,
# what ever you give the command via console that will override by cmd and 
#that will pass to entrypoint via cmd 

CMD ["google.com"]

ENTRYPOINT ["ping", "-c10"]