ARG VERISON
#FROM almalinux:${VERISON} # it will install only when the version value is given at the runtime,
#if not given then it will throw an error 

#from the below instrunction if version value is given at the run time that will be installed,
# if not given by default it will run version 8 

FROM almalinux:${VERISON:-8} 

RUN ECHO ${VERISON}